package com.codingspezis.android.metalonly.player.fragments;

import android.support.v4.app.Fragment;
import android.widget.TextView;

import com.codingspezis.android.metalonly.player.BuildConfig;
import com.codingspezis.android.metalonly.player.R;
import com.codingspezis.android.metalonly.player.utils.FeedbackMailer;

import org.androidannotations.annotations.AfterViews;
import org.androidannotations.annotations.Bean;
import org.androidannotations.annotations.Click;
import org.androidannotations.annotations.EFragment;
import org.androidannotations.annotations.ViewById;
import org.androidannotations.annotations.res.StringRes;

/**
 * Displays information about this app and links to github.
 */
@EFragment(R.layout.fragment_about)
public class AboutFragment extends Fragment {
    @StringRes
    String mailaddress_codingspezis, app_name;
    @ViewById
    TextView textAppVersion;

    @Bean
    FeedbackMailer feedbackMailer;

    @Click(R.id.buttonFeedback)
    void buttonFeedbackClicked() {
        feedbackMailer.sendEmail();
    }

    /**
     * updates the app version label to the version string generated by gradle
     */
    @AfterViews
    public void setAppVersionLabel() {
        textAppVersion.setText(BuildConfig.VERSION_NAME + " (" + BuildConfig.VERSION_CODE + ")");
    }
}
